"""
Vercel Serverless Function for Label Creation.
Endpoint: POST /api/create-labels

Creates labels on GitHub repository using user's PAT.
"""

import json
import os
import re
import logging
from http.server import BaseHTTPRequestHandler

import httpx

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Label colors
LABEL_COLORS = {
    "bug": "d73a4a",
    "feature": "a2eeef",
    "enhancement": "a2eeef",
    "documentation": "0075ca",
    "question": "d876e3",
    "help wanted": "008672",
    "good first issue": "7057ff",
    "priority": "fbca04",
    "critical": "b60205",
    "high": "d93f0b",
    "medium": "fbca04",
    "low": "0e8a16",
    "default": "ededed"
}


def get_color(label_name: str) -> str:
    """Get appropriate color for a label."""
    label_lower = label_name.lower()
    for key, color in LABEL_COLORS.items():
        if key in label_lower:
            return color
    return LABEL_COLORS["default"]


class handler(BaseHTTPRequestHandler):
    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_POST(self):
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()

        try:
            content_length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(content_length)
            data = json.loads(body)

            repo_url = data.get("repo_url", "")
            labels = data.get("labels", [])
            github_token = data.get("github_token", "")

            if not github_token:
                self.wfile.write(json.dumps({
                    "success": False,
                    "error": "GitHub token is required"
                }).encode())
                return

            match = re.match(r"https?://github\.com/([^/]+)/([^/]+)/?", repo_url)
            if not match:
                self.wfile.write(json.dumps({
                    "success": False,
                    "error": "Invalid GitHub URL"
                }).encode())
                return

            owner, repo = match.groups()

            headers = {
                "Accept": "application/vnd.github.v3+json",
                "Authorization": f"token {github_token}",
                "User-Agent": "Seedling-Issue-Assistant/1.0"
            }

            results = {
                "created": [],
                "existing": [],
                "failed": []
            }

            with httpx.Client(timeout=30) as client:
                for label in labels:
                    url = f"https://api.github.com/repos/{owner}/{repo}/labels"
                    payload = {
                        "name": label,
                        "color": get_color(label),
                        "description": "Auto-generated by Issue Assistant"
                    }

                    response = client.post(url, json=payload, headers=headers)

                    if response.status_code == 201:
                        results["created"].append(label)
                    elif response.status_code == 422:
                        results["existing"].append(label)
                    else:
                        results["failed"].append({
                            "label": label,
                            "error": response.text[:100]
                        })

            self.wfile.write(json.dumps({
                "success": True,
                "data": results
            }).encode())

        except Exception as e:
            logger.error(f"Error: {e}")
            self.wfile.write(json.dumps({
                "success": False,
                "error": str(e)
            }).encode())
